### ISSUE TITLE
giviing error on filters

### ISSUE THREAD

**Issue by egorzal** [husseycoding/customordergrid#3]
For example on order filter
Integrity constraint violation: 1052 Column 'increment_id' in where clause is ambiguous,

**Comment by husseycoding** [comment]
Can you test this on a clean install to see if you still get the same errors?

**Comment by sachittandukar** [comment]
@husseycoding on clean install, this issue appears.

The solution is to add following line of code on observer.php inside
`private function _addNewColumn($column, $block, $width)` method in line 107:
`$incrementIdColumn = $block->getColumn('real_order_id');`

```
    if($incrementIdColumn) {
        $incrementIdColumn->addData(array('filter_index' => 'main_table.increment_id'));
    }
```

**Comment by husseycoding** [comment]
Right ok thanks, I'll do some investigations and patch it for the next release - thanks.  You get this error if there are multiple tables with the same column so rather than add a filter_index (which is a totally valid fix) I'll probably instead remove the additional column, or use the filter_index is that isn't practical.
